language: node_js
node_js:
- '10'
branchs:
  only:
  - master
script:
- npm i -g hexo-cli
- npm i
before_install:
- git config user.name "linganmin"
- git config user.email "saboran@163.com"
- openssl aes-256-cbc -K $encrypted_09e65336fb9c_key -iv $encrypted_09e65336fb9c_iv
  -in ./.travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
deploy:
- provider: script
  script: 
  - bash .travis/deploy.sh prod
  
  - hexo generate
  - git commit -am "build success"
  - ls
  - pwd
  - rsync -azr -vv --delete  public/ travis@47.96.70.2:/data/wwwroot/www.sosad.cn/

  on:
    branch: master
